
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails-task_development


test:
  <<: *default
  database: rails-task_test


production:
  <<: *default
  database: rails-task_production
  username: rails-task
  password: <%= ENV['RAILS-TASK_DATABASE_PASSWORD'] %>
